#!/bin/bash
# First-run installer for Amnezia Cloak.
#
# Usage:  sudo install-helper.sh <bundled-helper-path> <invoking-user>
#
# Copies the bundled awg-helper into /usr/local/sbin, writes a NOPASSWD
# sudoers rule for the invoking user, and seeds /etc/amnezia/amneziawg.
# Called from the app via `osascript` + `with administrator privileges`
# so the user is prompted for their password exactly once.
#
# Idempotent — safe to re-run on upgrade.

set -eu

HELPER_SRC="${1:?missing helper source path}"
USER_NAME="${2:?missing invoking user}"

HELPER_DST=/usr/local/sbin/awg-helper
SUDOERS_DST=/etc/sudoers.d/amnezia-cloak
CONF_DIR=/etc/amnezia/amneziawg

[[ -f "$HELPER_SRC" ]] || { echo "helper source not found: $HELPER_SRC" >&2; exit 1; }
[[ "$USER_NAME" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "suspicious user name: $USER_NAME" >&2; exit 2; }

# 1. Install helper binary.
/usr/bin/install -d -m 755 /usr/local/sbin
/usr/bin/install -o root -g wheel -m 755 "$HELPER_SRC" "$HELPER_DST"

# 2. Seed config dir (helper also does this, but we want it ready on first launch).
/usr/bin/install -d -o root -g wheel -m 755 "$CONF_DIR"

# 3. Write sudoers rule. Use visudo -cf to validate before installing atomically.
SUDOERS_TMP="$(mktemp "${TMPDIR:-/tmp}/amnezia-cloak-sudoers.XXXXXX")"
cat > "$SUDOERS_TMP" <<EOF
# Amnezia Cloak — generated by install-helper.sh
$USER_NAME ALL=(root) NOPASSWD: $HELPER_DST
$USER_NAME ALL=(root) NOPASSWD: /bin/cat $CONF_DIR/*.conf
EOF
/usr/sbin/visudo -cf "$SUDOERS_TMP" >/dev/null \
    || { echo "sudoers validation failed" >&2; /bin/rm -f "$SUDOERS_TMP"; exit 3; }
/usr/bin/install -o root -g wheel -m 440 "$SUDOERS_TMP" "$SUDOERS_DST"
/bin/rm -f "$SUDOERS_TMP"

echo "ok"
