#!/bin/bash
# First-run installer for Amnezia Cloak.
#
# Usage:  sudo install-helper.sh <bundle-resources-dir> <invoking-user>
#
# bundle-resources-dir points at the .app's Contents/Resources directory,
# so we can pick up both the helper script AND any prebuilt CLI binaries
# (awg, awg-quick, amneziawg-go) that the release workflow placed under
# bin/. The release DMG ships all of these; a local dev build ships only
# the helper.
#
# Installed:
#   /usr/local/sbin/awg-helper          (0755 root:wheel)
#   /usr/local/bin/awg                  (if bundled)
#   /usr/local/bin/awg-quick            (if bundled)
#   /usr/local/bin/amneziawg-go         (if bundled)
#   /etc/sudoers.d/amnezia-cloak        (0440 root:wheel, NOPASSWD scoped)
#   /etc/amnezia/amneziawg/             (0755 root:wheel)
#
# Called from the app via `osascript` + `with administrator privileges` so
# the user is prompted for their password exactly once. Idempotent — safe
# to re-run on upgrade.

set -eu

RESOURCES="${1:?missing bundle resources directory}"
USER_NAME="${2:?missing invoking user}"

HELPER_SRC="$RESOURCES/awg-helper"
HELPER_DST=/usr/local/sbin/awg-helper
BIN_SRC="$RESOURCES/bin"
BIN_DST=/usr/local/bin
LIBEXEC_DST=/usr/local/libexec/amnezia-cloak
SUDOERS_DST=/etc/sudoers.d/amnezia-cloak
CONF_DIR=/etc/amnezia/amneziawg

[[ -f "$HELPER_SRC" ]] || { echo "helper source not found: $HELPER_SRC" >&2; exit 1; }
[[ "$USER_NAME" =~ ^[A-Za-z0-9._-]+$ ]] || { echo "suspicious user name: $USER_NAME" >&2; exit 2; }

# 1. Install helper binary.
/usr/bin/install -d -m 755 /usr/local/sbin
/usr/bin/install -o root -g wheel -m 755 "$HELPER_SRC" "$HELPER_DST"

# 2. Install CLI binaries (awg, awg-quick, amneziawg-go) if the .app bundles
#    them. Strip the com.apple.quarantine xattr so Gatekeeper doesn't block
#    exec from awg-quick / awg-helper.
if [[ -d "$BIN_SRC" ]]; then
    /usr/bin/install -d -m 755 "$BIN_DST"
    for bin in awg awg-quick amneziawg-go; do
        src="$BIN_SRC/$bin"
        [[ -f "$src" ]] || continue
        /usr/bin/install -o root -g wheel -m 755 "$src" "$BIN_DST/$bin"
        /usr/bin/xattr -d com.apple.quarantine "$BIN_DST/$bin" 2>/dev/null || true
    done
fi

# 2b. Install bundled bash 5 into a private libexec dir. macOS ships bash 3.2
#     at /bin/bash (stuck on that version for GPL2-licensing reasons), but
#     awg-quick's darwin.bash uses bash 4+ features (associative arrays, etc).
#     We install to a private path instead of /usr/local/bin so we don't clash
#     with anyone's Homebrew bash; awg-helper prepends this dir to PATH before
#     calling awg-quick, so `#!/usr/bin/env bash` picks up our build.
if [[ -f "$BIN_SRC/bash" ]]; then
    /usr/bin/install -d -o root -g wheel -m 755 "$LIBEXEC_DST"
    /usr/bin/install -o root -g wheel -m 755 "$BIN_SRC/bash" "$LIBEXEC_DST/bash"
    /usr/bin/xattr -d com.apple.quarantine "$LIBEXEC_DST/bash" 2>/dev/null || true
fi

# 3. Seed config dir (helper also does this, but we want it ready on first launch).
/usr/bin/install -d -o root -g wheel -m 755 "$CONF_DIR"

# 4. Write sudoers rule. Use visudo -cf to validate before installing atomically.
SUDOERS_TMP="$(mktemp "${TMPDIR:-/tmp}/amnezia-cloak-sudoers.XXXXXX")"
cat > "$SUDOERS_TMP" <<EOF
# Amnezia Cloak — generated by install-helper.sh
$USER_NAME ALL=(root) NOPASSWD: $HELPER_DST
$USER_NAME ALL=(root) NOPASSWD: /bin/cat $CONF_DIR/*.conf
EOF
/usr/sbin/visudo -cf "$SUDOERS_TMP" >/dev/null \
    || { echo "sudoers validation failed" >&2; /bin/rm -f "$SUDOERS_TMP"; exit 3; }
/usr/bin/install -o root -g wheel -m 440 "$SUDOERS_TMP" "$SUDOERS_DST"
/bin/rm -f "$SUDOERS_TMP"

echo "ok"
